version: "3"

services:
  bot:
    image: seleznev/air_bot:latest
    restart: always
    container_name: air_bot
    build:
      dockerfile: Dockerfile
      context: "."
      args:
        CGO_ENABLED: 0
        GOOS: linux
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "./.data/:/data/"
      - "./example/config.yaml:/config.yaml"
    environment:
      - CONFIG_PATH=/config.yaml
      - TOKEN=${TELEGRAM_BOT_TOKEN}